blood_donation_project/blood_donation_app/urls.py
from django.urls import path,include
from blood_donation_app import views
from .views import *

urlpatterns=[
    path("",views.index,name="index"),
    path("add_donor/",views.add_donor,name="add_donor"),
    path('add_bloodbank/', views.add_bloodbank, name='add_bloodbank'),
    path('donorlist/',views.donorlist,name="donorlist"),
    path('admin_login_view/',views.admin_login,name="admin_login"),
    path('delete_donor/<str:donor_email>/',views.delete_donor,name="delete_donor"),
    path('edit_donor/<str:donor_email>/', views.edit_donor, name="edit_donor"),
    path('donation_records/',views.donation_record,name="donation_record"),
    path('bloodbanklist/',views.bloodbanklist,name="bloodbanklist"),
    path('admin_login/',views.admin_login_view,name="admin_login_view"),
    path('register/',RegisterUser.as_view()),
    path('orm/', my_view, name='my_view'),
    path('statistics/',views.display_blood_donation_statistics,name="display_blood_donation_statistics"),
]   

blood_donation_project/blood_donation_project/urls.py
from django.contrib import admin
from django.urls import path,include 
from blood_donation_app import urls 
from rest_framework.authtoken import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include(urls)),
    path('api-token-auth/',views.obtain_auth_token),
]

blood_donation_project/blood_donation_app/models.py
from django.db import models


from storages.backends.s3boto3 import S3Boto3Storage

class S3MediaStorage(S3Boto3Storage):
    location = 'media'
    file_overwrite = False
# Create your models here.
    
class BloodType(models.Model):
    blood_type=models.CharField(max_length=20)

    def __str__(self):
        return self.blood_type




class BloodBank(models.Model):
    bloodbank_name=models.CharField(max_length=50,primary_key=True)
    bloodbank_location=models.CharField(max_length=100)
    bloodbank_phone=models.CharField(max_length=10)
    Opositive_units=models.IntegerField(null=True, blank=True)
    Onegative_units=models.IntegerField(null=True, blank=True)
    Apositive_units=models.IntegerField(null=True, blank=True)
    Anegative_units=models.IntegerField(null=True, blank=True)
    Bpositive_units=models.IntegerField(null=True, blank=True)
    Bnegative_units=models.IntegerField(null=True, blank=True)
    ABpositive_units=models.IntegerField(null=True, blank=True)
    ABnegative_units=models.IntegerField(null=True, blank=True)




class Donor(models.Model):
    donor_name=models.CharField(max_length=30)
    donor_photo=models.ImageField(upload_to='media',storage=S3MediaStorage(),null=True,blank=True)
    donor_email=models.EmailField(primary_key=True)
    donor_blood_type=models.ForeignKey(BloodType,on_delete=models.CASCADE,)
    donor_phone=models.CharField(max_length=10)
    bloodbank=models.ForeignKey(BloodBank,on_delete=models.CASCADE)
    last_donation_date=models.DateField(default=None)

    def __str__(self):
        return self.donor_name







class DonationRecord(models.Model):
    donor=models.ForeignKey(Donor,on_delete=models.CASCADE,to_field="donor_email")
    bloodbank=models.ForeignKey(BloodBank,on_delete=models.CASCADE,to_field="bloodbank_name")
    donation_date=models.DateField()
    def __str__(self):
        return self.donor.donor_name+" "+self.bloodbank.bloodbank_name

blood_donation_project/blood_donation_app/forms.py
from django import forms
from .models import Donor,BloodBank

class DonorForm(forms.ModelForm):
    class Meta:
        model = Donor
        fields = ['donor_name', 'donor_phone']
    
   

blood_donation_project/blood_donation_app/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse,HttpResponseRedirect
from .models import*
from .serializers import *
from django.db import IntegrityError
from django.shortcuts import get_object_or_404
from .forms import *
from .forms import DonorForm
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required,user_passes_test
from rest_framework.views import APIView
from rest_framework.authtoken.models import Token
from rest_framework.response import Response
from rest_framework.decorators import api_view
from .orm_filters import filter_donations_by_criteria
from datetime import datetime
# Create your views here.

def index(request):
    return render(request,'home.html')
from django.db.models import F

def update_quantity(bloodbank, bloodtype):
    try:
        blood_bank = BloodBank.objects.get(bloodbank_name=bloodbank)
    except BloodBank.DoesNotExist:
        print("Blood bank not found:", bloodbank)
        return
    if bloodtype == "O+":
        BloodBank.objects.filter(pk=blood_bank.pk).update(Opositive_units=F('Opositive_units') + 1)
    elif bloodtype == "O-":
        BloodBank.objects.filter(pk=blood_bank.pk).update(Onegative_units=F('Onegative_units') + 1)
    elif bloodtype == "A+":
        BloodBank.objects.filter(pk=blood_bank.pk).update(Apositive_units=F('Apositive_units') + 1)
    elif bloodtype == "A-":
        BloodBank.objects.filter(pk=blood_bank.pk).update(Anegative_units=F('Anegative_units') + 1)
    elif bloodtype == "B+":
        BloodBank.objects.filter(pk=blood_bank.pk).update(Bpositive_units=F('Bpositive_units') + 1)
    elif bloodtype == "B-":
        BloodBank.objects.filter(pk=blood_bank.pk).update(Bnegative_units=F('Bnegative_units') + 1)
    elif bloodtype == "AB+":
        BloodBank.objects.filter(pk=blood_bank.pk).update(ABpositive_units=F('ABpositive_units') + 1)
    elif bloodtype == "AB-":
        BloodBank.objects.filter(pk=blood_bank.pk).update(ABnegative_units=F('ABnegative_units') + 1)
    else:
        print("Invalid blood type:", bloodtype)
        print(type(bloodtype))
        return




@login_required(login_url='/admin_login/')
def add_donor(request):
    if request.method == 'POST':
        donor_serializer=DonorSerializers(data=request.POST)
        if donor_serializer.is_valid():
            try:
                donor=donor_serializer.save()
                update_quantity(donor.bloodbank.bloodbank_name,donor.donor_blood_type.blood_type)
                donation_record_data = {
                    'donor': donor.donor_email,
                    'bloodbank': donor.bloodbank.bloodbank_name,
                    'donation_date': donor.last_donation_date, 
                }
                donation_record_serializer = DonationRecordSerializers(data=donation_record_data)
                print(donation_record_data)
                if donation_record_serializer.is_valid():
                    donation_record_serializer.save()
                else:
                    print(donation_record_serializer.errors)
                    print("Donation Record validation failed")
                return redirect('/')
            except IntegrityError:
                print('record exists')
                return redirect("/")
        else:
           
            existing_donor = Donor.objects.get(donor_email=request.POST['donor_email'])
            bloodbank_name = request.POST['bloodbank']
            last_donation_date = request.POST['last_donation_date']
            bloodbank_instance = BloodBank.objects.get(bloodbank_name=bloodbank_name)
            existing_donor.bloodbank = bloodbank_instance
            existing_donor.last_donation_date = last_donation_date  
            existing_donor.save()
            
            donation_record_data = {
                'donor': existing_donor.donor_email,
                'bloodbank': existing_donor.bloodbank.bloodbank_name,
                'donation_date': existing_donor.last_donation_date,
            }
            print(donation_record_data)
            donation_record_serializer = DonationRecordSerializers(data=donation_record_data)
            
            if donation_record_serializer.is_valid():
                donation_record_serializer.save()
                
                update_quantity(existing_donor.bloodbank.bloodbank_name, existing_donor.donor_blood_type.blood_type)
                return redirect('/')
            else:
                print(donation_record_serializer.errors)
                print("Donation Record validation failed")
                return redirect('/')
    
    blood_banks = BloodBank.objects.all()
    bloodtypes = BloodType.objects.all()
    return render(request, 'add_donor.html', {"bloodtypes": bloodtypes, "blood_banks": blood_banks})


@login_required(login_url='/admin_login/')
@api_view(['GET'])
def donorlist(request):
    donors=Donor.objects.all()
    serializer=DonorSerializers(donors,many=True)
    serialized_data=serializer.data
    print(serialized_data)
    return render(request,'donorlist.html',{'d':serialized_data})


def delete_donor(request,donor_email):
    donor_to_delete=get_object_or_404(Donor,donor_email=donor_email)
    donor_to_delete.delete()
    return redirect('/donorlist')



def edit_donor(request, donor_email):
    donor = get_object_or_404(Donor, donor_email=donor_email)

    if request.method == 'POST':
        form = DonorForm(request.POST, instance=donor)
        if form.is_valid():
            form.save()
            return redirect('/donorlist')
    else:
        form = DonorForm(instance=donor)
    return render(request, 'edit_donor.html', {'form': form, 'donor': donor})



@login_required(login_url='/admin_login/')
def donation_record(request):
    donation_records=DonationRecord.objects.all()
    return render(request,'donationrecord.html',{'donation_records': donation_records})

@login_required(login_url='/admin_login/')
def add_bloodbank(request):
    if request.method == 'POST':
        bloodbank_serializer=BloodBankSerializers(data=request.POST)
        if bloodbank_serializer.is_valid():
            try:
                bloodbank=bloodbank_serializer.save()
                return redirect('/')
            except IntegrityError:
                print('record exists')
                return redirect("/")
        else:
            print(bloodbank_serializer.errors)
            print("validation failed")
            return redirect('/') 
    return render(request, 'add_bloodbank.html')


@login_required(login_url='/admin_login/')
def bloodbanklist(request):
    data=BloodBank.objects.all()
    return render(request,'bloodbanklist.html',{'data':data})





from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect

def admin_login_view(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        admin = authenticate(request, username=username, password=password)
        if admin is not None:
            login(request, admin)
            return redirect('/')
        else:
            # Authentication failed
            error_message = "Invalid username or password. Please try again."
            return render(request, 'admin_login.html', {'error_message': error_message})
    else:
        # Handle GET request - render login form
        return render(request, 'admin_login.html')



def admin_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        admin = authenticate(request, username=username, password=password)
        if admin is not None:
            login(request, admin)
            return redirect('/admin/')
        else:
            # Authentication failed
            error_message = "Invalid username or password. Please try again."
            return render(request, 'admin_login.html', {'error_message': error_message})
    else:
        return render(request, 'admin_login.html')





class RegisterUser(APIView):
    def post(self,request):
        serializer=UserSerializer(data=request.data)
        if not serializer.is_valid():
            return Response({'status':403,'errors':serializer.errors,'message':'Somethinng went wrong'})
        serializer.save()
        user=User.objects.get(username=serializer.data['username'])
        token_obj,_=Token.objects.get_or_create(user=user)
        return Response({'status':200,'payload':serializer.data,'message':'Your data is saved '})
    





def my_view(request):

    start_date = datetime(2024, 2, 5)
    end_date = datetime(2024, 2, 16)
    blood_type = 'O+'
    filtered_donations = filter_donations_by_criteria(blood_type, start_date, end_date)
    print(filtered_donations)
    return render(request, 'filtered_donations.html', {'filtered_donations': filtered_donations})


from django.shortcuts import render
from .statistics import total_blooddonation_of_each_type

def display_blood_donation_statistics(request):
    blood_type_totals_dict = total_blooddonation_of_each_type()
    return render(request, 'statistics.html', {'blood_type_totals_dict': blood_type_totals_dict})

blood_donation_project/blood_donation_app/templates/add_bloodbank.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Blood Bank</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/add_bloodbank.css' %}">
</head>

<body>
    <h2 style="text-align: center;">Add Blood Bank Details</h2>
    <form action="{% url 'add_bloodbank' %}" method="POST">
        {% csrf_token %}
        <label for="bloodbank_name">Blood Bank Name:</label>
        <input type="text" id="bloodbank_name" name="bloodbank_name" required>
        
        <label for="bloodbank_location">Blood Bank Location:</label>
        <input type="text" id="bloodbank_location" name="bloodbank_location" required>
        
        <label for="bloodbank_phone">Blood Bank Phone:</label>
        <input type="text" id="bloodbank_phone" name="bloodbank_phone" required>
        
        <label for="Opositive_units">O+ Units:</label>
        <input type="number" id="Opositive_units" name="Opositive_units" required>
        
        <label for="Onegative_units">O- Units:</label>
        <input type="number" id="Onegative_units" name="Onegative_units" required>
        
        <label for="Apositive_units">A+ Units:</label>
        <input type="number" id="Apositive_units" name="Apositive_units" required>
        
        <label for="Anegative_units">A- Units:</label>
        <input type="number" id="Anegative_units" name="Anegative_units" required>
        
        <label for="Bpositive_units">B+ Units:</label>
        <input type="number" id="Bpositive_units" name="Bpositive_units" required>
        
        <label for="Bnegative_units">B- Units:</label>
        <input type="number" id="Bnegative_units" name="Bnegative_units" required>
        
        <label for="ABpositive_units">AB+ Units:</label>
        <input type="number" id="ABpositive_units" name="ABpositive_units" required>
        
        <label for="ABnegative_units">AB- Units:</label>
        <input type="number" id="ABnegative_units" name="ABnegative_units" required>
        
        <input type="submit" value="Submit">
    </form>
</body>
</html>

blood_donation_project/blood_donation_app/templates/add_donor.html
 <!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add_Donor</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/add_donor.css' %}">
</head>
<body>
    <h1 style="text-align: center; color:red">Add Donor Details</h1>
    <form action="{% url 'add_donor' %}" method="POST">
    {% csrf_token %}
    <div class="container">
        <table>
            <tr>
                <td><label for="id_donor_name">Donor Name</label></td>
                <td><input type="text" name="donor_name" id="id_donor_name" required><br></td>
            </tr>
            <tr>
                <td><label for="id_donor_email">Email</label></td>
                <td><input type="email" name="donor_email" id="id_donor_email" required><br></td>
            </tr>
            <tr>
                <td><label for="id_blood_type">Blood Type</label></td>
                <td>
                    <select name="donor_blood_type" id="id_blood_type" required>
                        {% for bloodtype in bloodtypes %}
                            <option value="{{ bloodtype.id }}">{{ bloodtype.blood_type }}</option>
                        {% endfor %}
                    </select>
                </td>
            </tr>
            <tr>
                <td><label for="id_donor_phone">Contact No</label></td>
                <td><input type="tel" name="donor_phone" id="id_donor_phone" pattern="[0-9]{10}" required><br></td>
            </tr>
            <tr>
                <td><label for="id_blood_bank">Blood Bank</label></td>
                <td>
                    <select name="bloodbank" id="id_blood_bank" required>
                        {% for bloodbank in blood_banks %}
                            <option value="{{ bloodbank.bloodbank_name }}">{{bloodbank.bloodbank_name}}</option>
                        {% endfor %}
                    </select>
                </td>
            </tr>
            <tr>
                <td><label for="id_last_donation_date">Last donation record (Today)</label></td>
                <td><input type="date" name="last_donation_date" id="id_last_donation_date" required><br></td>
            </tr>
        </table>
    </div>
    <button type="submit">Submit</button>
</form>

      <script>
        function showPopup() {
          alert("Data saved Successfully");
        }

    </script>
 </body>
</html>

blood_donation_project/blood_donation_app/templates/admin_login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Login</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/admin_login.css' %}">

</head>
<body>
    <div class="login-container">
        <h2>Admin Login</h2>
        <form action="" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="username">Username:</label>
                <input type="text" id="username" name="username" required>
            </div>
            <div class="form-group">
                <label for="password">Password:</label>
                <input type="password" id="password" name="password" required>
            </div>
            <button type="submit" class="login-button">Login</button>
        </form>
        {% if error_message %}
        <p class="error-message">{{ error_message }}</p>
        {% endif %}
    </div>
</body>
</html>

blood_donation_project/blood_donation_app/templates/bloodbanklist.html
<!-- my_template.html -->
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blood Banks Record</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bloodbanklist.css' %}">

</head>
<body>
    
        <h1 style="text-align: center;">Blood Bank Names</h1>

        <table >
            <thead>
                <tr>
                    <th>Bloodbank Name</th>
                    <th>Location</th>
                    <th>Contact</th>
                    <th>O+(UNITS)</th>
                    <th>O-(UNITS)</th>
                    <th>A+(UNITS)</th>
                    <th>A-(UNITS)</th>
                    <th>B+(UNITS)</th>
                    <th>B-(UNITS)</th>
                    <th>AB+(UNITS)</th>
                    <th>AB-(UNITS)</th>
                </tr>
            </thead>
            <tbody>
                {% for item in data %}
                    <tr style="text-align: center;">
                        <td>{{ item.bloodbank_name }}</td>
                        <td>{{ item.bloodbank_location }}</td>
                        <td>{{item.bloodbank_phone}}</td>
                        <td>{{item.Opositive_units}}</td>
                        <td>{{item.Onegative_units}}</td>
                        <td>{{item.Apositive_units}}</td>
                        <td>{{item.Anegative_units}}</td>
                        <td>{{item.Bpositive_units}}</td>
                        <td>{{item.Bnegative_units}}</td>
                        <td>{{item.ABpositive_units}}</td>
                        <td>{{item.ABnegative_units}}</td>

                    </tr>
                {% endfor %}
            </tbody>
        </table>
    
    

   
</body>
</html>

blood_donation_project/blood_donation_app/templates/donationrecord.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Donation Records</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/donationrecord.css' %}">
    <style>
        /* CSS for positioning the back button */
        .back-button {
            position: absolute;
            top: 10px; /* Adjust this value to position vertically */
            right: 10px; /* Adjust this value to position horizontally */
            color: white;
            background-color: #333;
            padding: 8px 16px;
            border-radius: 5px;
            text-decoration: none;
        }
    </style>
</head>
<nav>
    <div class="navbar">
        <h1>Donor's List</h1>
        <div class="navbar-right">
            <a href="{% url 'index' %}" class="back-button">Back to Home</a>
        </div>
    </div>
</nav>

<body>
    <h1>Donation Records</h1>
    
    <table>
        <thead>
            <tr>
                <th>Donor</th>
                <th>Blood Bank</th>
                <th>Donation Date</th>
            </tr>
        </thead>
        <tbody>
            {% for record in donation_records %}
                <tr>
                    <td>{{ record.donor.donor_name }}</td>
                    <td>{{ record.bloodbank.bloodbank_name }}</td>
                    <td>{{ record.donation_date }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
</html>

blood_donation_project/blood_donation_app/templates/donorlist.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Find Donor</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/donorlist.css' %}">
    <style>
        /* CSS for positioning the back button */
        .back-button {
            position: absolute;
            top: 10px; /* Adjust this value to position vertically */
            right: 10px; /* Adjust this value to position horizontally */
            color: white;
            background-color: #333;
            padding: 8px 16px;
            border-radius: 5px;
            text-decoration: none;
        }
    </style>
</head>
<body>
    <nav>
        <div class="navbar">
            <h1>Donor's List</h1>
            <div class="navbar-right">
                <a href="{% url 'index' %}" class="back-button">Back to Home</a>
            </div>
        </div>
    </nav>
    

    <table>
        <thead>
            <tr>
                <th>Donor Name</th>
                <th>Email</th>
                <th>Blood Type</th>
                <th>Contact Number</th>
                <th>Blood Bank</th>
                <th>Last Donation Record</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            {% for item in d %}
            <tr>
                <td>{{ item.donor_name }}</td>
                <td>{{ item.donor_email }}</td>
                <td>{{ item.donor_blood_type }}</td>
                <td>{{ item.donor_phone }}</td>
                <td>{{ item.bloodbank }}</td>
                <td>{{ item.last_donation_date }}</td>
                <td>
                    <form action="{% url 'delete_donor' item.donor_email %}" method="post">
                        {% csrf_token %}
                        <button type="submit">Delete</button>
                    </form>
                </td> 
                <td>
                    <form action="{% url 'edit_donor' item.donor_email %}" method="get">
                        {% csrf_token %}
                        <button type="submit">Edit</button>
                    </form>
                </td> 
            </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
</html>

blood_donation_project/blood_donation_app/templates/edit_donor.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit donor </title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/edit_donor.css' %}">
</head>
<body>
    <h1>EDIT DONOR DETAILS</h1>
    <form method="post" action="{% url 'edit_donor' donor.donor_email %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Update Donor</button>
    </form>
</body>
</html>

blood_donation_project/blood_donation_app/templates/filtered_donations.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Filtered Donations</title>
</head>
<body>
    <h1>Filtered Donations</h1>
    <ul>
        {% for donation in filtered_donations %}
        <li>Donor: {{ donation.donor.donor_name }}, Blood Bank: {{ donation.bloodbank.bloodbank_name }}</li>
        {% endfor %}
    </ul>
</body>
</html>

blood_donation_project/blood_donation_app/templates/home.html
<!DOCTYPE html>
{% load static %}

<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Blood Bank - Your Source of Life</title>
  <link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}">
</head>

<body>
  <nav class="navbar">
    <div class="navbar-logo">
      <img src="https://img.freepik.com/free-vector/x9beautiful-hands-saving-blood-drop-card-design_1035-23347.jpg?size=626&ext=jpg&ga=GA1.1.1412446893.1704844800&semt=ais"
        alt="Blood Bank Logo" class="logo-image">
      <div class="logo-text">Blood Bank</div>
    </div>

    <ul class="nav-links">
      <li><a href="#" class="nav-link red-bg">Home</a></li>
      <li><a href="#" class="nav-link red-bg">About Us</a></li>
      <li><a href="add_donor/" class="nav-link red-bg">Add Donor</a></li>
      <li><a href="add_bloodbank/" class="nav-link red-bg">Add Blood Bank</a></li>
    </ul>
  </nav>

  <div class="container">
    <div>
      <p>Save Blood Save Life</p>
    </div>
    <div>
      <!-- <button id="myButton">Admin Login</button> -->
      
      <a href="admin_login/" class="box-button">Admin_login</a>
      <!-- <a href=""></a> -->
    </div>
  </div>

<div class="bottom-boxes-container">
  <div class="box">
    <div class="box-header">
      
      <h2>Donor's List</h2>
    </div>
    <p>Donors are the real hero's to save other's life.</p><br>
    <a href="donorlist/" class="box-button">Click</a>
    <!-- <button class="box-button" type="submit">Button 1</button> -->
  </div>

  <div class="box">
    <div class="box-header">
      <h2>Donation Records</h2>
    </div>
    <p>Click the button to see donation records </p><br>
    <a href="donation_records/" class="box-button">Click</a>
  </div>

  <div class="box">
    <div class="box-header">
      
      <h2>Blood Banks </h2>
    </div>
    <p>click to see bloodbanks</p><br>
    <a href="bloodbanklist/" class="box-button">Click</a>
  </div>
</div>

  <script>
    document.getElementById("myButton").addEventListener("click", function () {
      window.location.href = "admin/login/?next=/admin/";
    });
  </script>
</body>

</html>

blood_donation_project/blood_donation_app/templates/statistics.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blood Donation Statistics</title>
</head>
<body>
    <h1>Blood Donation Statistics</h1>
    <table>
        <thead>
            <tr>
                <th>Blood Type</th>
                <th>Total Donations</th>
            </tr>
        </thead>
        <tbody>
            {% for blood_type, total_donations in blood_type_totals_dict.items %}
            <tr>
                <td>{{ blood_type }}</td>
                <td>{{ total_donations }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
</html>